### PR TITLE
Initial investigation trying to get this to build via the provided Makefile generators

### PR DESCRIPTION
**Pull request by dorchard**
I haven't quite figured it out yet, but made some progress.

### CODE REVIEW

**Comment by dorchard** [comment]
I've got the makefile in a shape where it is "doing the right thing" but I can't get the code to compile with either gfortran or ifort due to varying issues around what looks like types. Needs some investigations. Will also raise an issue on the home repo.

**Comment by dorchard** [comment]
https://github.com/yaniyuval/Neural_nework_parameterization/issues/2 
Have asked here. I think the next issue seems to be in choosing which "RAD" library to pull in.

**Comment by jatkinson1000** [comment]
Splitting the line can be negated with the `-ffree-line-length-none` flag in gfortran.
Source code is available [here](http://rossby.msrc.sunysb.edu/~marat/SAM/) which includes _a_ MakeFile which may help.

**Comment by jatkinson1000** [comment]
This should be addressed in the PR #3 so I am closing this PR and deleting the associated branch.

**Comment by dorchard** [comment]
Good. Thanks!

**Pull request closed without merging**
